language: node_js
node_js:
  - 'node'
  - '10'
  - '8'
env:
  - CODECOV_TOKEN="f9e6550c-0f4f-4618-b107-b6f5bea39879"
branches:
  only:
    - master
    - /^release-.*/
    -
script:
  - npm ci
  - npm run test
  - npm install codecov -g
after_success:
  - codecov
